------CAR RENTAL MANAGEMENT SYSTEM  DATABASE-----

-----CREATING DATABASE-----
CREATE DATABASE CRMS 

-----USING STATEMENT------
USE CRMS

-----DROPING STATEMENT-----
--DROP DATABASE CRMS

/*

CREATION DATE: 15-DEC-2022

NO. OF TABLES:
NO. OF CONSTRAINST: 
TABLE NAMES:

*/

-----CREATING CUSTOMER TABLE-----

CREATE TABLE CUSTOMER (

FNAME VARCHAR(10) NOT NULL,
LNAME VARCHAR(10) NOT NULL,
PHONE_NO VARCHAR(14) UNIQUE NOT NULL,
NIC_NO VARCHAR(15) UNIQUE NOT NULL,
CADDRESS VARCHAR(30) NOT NULL,
DL_NO VARCHAR(10) PRIMARY KEY                                      --DRIVING LICENSE NUMBER--

)

-----CREATING CAR_CATEGORY TABLE-----


CREATE TABLE CAR_CATEGORY (

CATEGORY_NAME VARCHAR(11) PRIMARY KEY ,
NO_OF_PERSON INT NOT NULL,
COST_PER_DAY MONEY NOT NULL

)

-----CREATING CAR TABLE-----

CREATE TABLE CAR_DETAILS (

REGISTRATION_NO VARCHAR(6) PRIMARY KEY,
CAR_NAME VARCHAR(8) NOT NULL,
MAKE VARCHAR(10) NOT NULL,
MODEL_NAME VARCHAR(10) NOT NULL,
CATEGORY_NAME VARCHAR(11) FOREIGN KEY REFERENCES CAR_CATEGORY(CATEGORY_NAME) NOT NULL
)



-----CREATING BOOKING DETAILS TABLE-----

CREATE TABLE BOOKING_DETAILS (

BOOKING_ID INT PRIMARY KEY IDENTITY(0001,1),
DATE_OUT DATE ,
DATE_BACK DATE ,
DL_NO VARCHAR(10) FOREIGN KEY REFERENCES CUSTOMER(DL_NO),
REGISTRATION_NO VARCHAR(6) FOREIGN KEY REFERENCES CAR_DETAILS(REGISTRATION_NO)
)


-----CREATING BILING DETAILS TABLE-----

CREATE TABLE BILLING_DETAILS (

BILL_ID INT PRIMARY KEY IDENTITY(1,1),
BILL_DATE DATE ,
TOTAL_AMOUNT  MONEY,
BOOKING_ID INT FOREIGN KEY REFERENCES BOOKING_DETAILS(BOOKING_ID)
)


------INSERTING DATA INTO TABLE CAR_CATEGORY

INSERT INTO CAR_CATEGORY (CATEGORY_NAME, NO_OF_PERSON, COST_PER_DAY) VALUES ('Compact', 4, 50.00)
INSERT INTO CAR_CATEGORY (CATEGORY_NAME, NO_OF_PERSON, COST_PER_DAY) VALUES ('Full-Size', 5, 75.00)
INSERT INTO CAR_CATEGORY (CATEGORY_NAME, NO_OF_PERSON, COST_PER_DAY) VALUES ('SUV', 7, 100.00)
INSERT INTO CAR_CATEGORY (CATEGORY_NAME, NO_OF_PERSON, COST_PER_DAY) VALUES ('Luxury', 4, 150.00)
INSERT INTO CAR_CATEGORY (CATEGORY_NAME, NO_OF_PERSON, COST_PER_DAY) VALUES ('Sports', 2, 200.00)
INSERT INTO CAR_CATEGORY (CATEGORY_NAME, NO_OF_PERSON, COST_PER_DAY) VALUES ('Convertible', 4, 125.00)
INSERT INTO CAR_CATEGORY (CATEGORY_NAME, NO_OF_PERSON, COST_PER_DAY) VALUES ('Van', 8, 80.00)
INSERT INTO CAR_CATEGORY (CATEGORY_NAME, NO_OF_PERSON, COST_PER_DAY) VALUES ('Minivan', 7, 90.00)
INSERT INTO CAR_CATEGORY (CATEGORY_NAME, NO_OF_PERSON, COST_PER_DAY) VALUES ('Truck', 3, 60.00)
INSERT INTO CAR_CATEGORY (CATEGORY_NAME, NO_OF_PERSON, COST_PER_DAY) VALUES ('Coupe', 2, 150.00)

------INSERTING DATA INTO TABLE CAR_DETAILS

INSERT INTO CAR_DETAILS (REGISTRATION_NO, CAR_NAME, MAKE, MODEL_NAME, CATEGORY_NAME) VALUES ('ABC123', 'Accord', 'Honda', 'EX', 'Compact')
INSERT INTO CAR_DETAILS (REGISTRATION_NO, CAR_NAME, MAKE, MODEL_NAME, CATEGORY_NAME) VALUES ('DEF456', 'Camry', 'Toyota', 'LE', 'Full-Size')
INSERT INTO CAR_DETAILS (REGISTRATION_NO, CAR_NAME, MAKE, MODEL_NAME, CATEGORY_NAME) VALUES ('GHI789', 'Escape', 'Ford', 'XLT', 'SUV')
INSERT INTO CAR_DETAILS (REGISTRATION_NO, CAR_NAME, MAKE, MODEL_NAME, CATEGORY_NAME) VALUES ('JKL012', 'A6', 'Audi', 'Premium', 'Luxury')
INSERT INTO CAR_DETAILS (REGISTRATION_NO, CAR_NAME, MAKE, MODEL_NAME, CATEGORY_NAME) VALUES ('MNO345', '370Z', 'Nissan', 'Sport', 'Sports')
INSERT INTO CAR_DETAILS (REGISTRATION_NO, CAR_NAME, MAKE, MODEL_NAME, CATEGORY_NAME) VALUES ('PQR678', 'Mustang', 'Ford', 'GT', 'Sports')
INSERT INTO CAR_DETAILS (REGISTRATION_NO, CAR_NAME, MAKE, MODEL_NAME, CATEGORY_NAME) VALUES ('STU901', 'Sienna', 'Toyota', 'LE', 'Minivan')
INSERT INTO CAR_DETAILS (REGISTRATION_NO, CAR_NAME, MAKE, MODEL_NAME, CATEGORY_NAME) VALUES ('VWX234', 'Tahoe', 'Chevrolet', 'LS', 'SUV')
INSERT INTO CAR_DETAILS (REGISTRATION_NO, CAR_NAME, MAKE, MODEL_NAME, CATEGORY_NAME) VALUES ('YZ0567', 'F-150', 'Ford', 'XL', 'Truck')
INSERT INTO CAR_DETAILS (REGISTRATION_NO, CAR_NAME, MAKE, MODEL_NAME, CATEGORY_NAME) VALUES ('789GHI', '3 Series', 'BMW', '330i', 'Sports')


-----SELECT STATEMENTS-----
select * from CUSTOMER
select * from BILLING_DETAILS
select * from CAR_CATEGORY
select * from CAR_DETAILS 
select * from BOOKING_DETAILS